config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations' }
  resources :feedback, only: %i[new create]
  resources :tests, only: :index do
    member do
      post :start
    end
  end
  resources :badges, only: :index
  resources :test_passages, only: %i[show update] do
    member do
      get :result # GET /tests_passages/10/result
      post :gist
    end
  end
  namespace :admin do
    resources :gists, only: :index
    resources :badges
    root 'tests#index'

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :users_badge
  has_many :users, through: :users_badge
  validates :title, :img, :rule, :value, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, presence: true
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

module Admin
  class BadgesController < ApplicationController
    before_action :set_badge, only: %i[index]
    layout 'admin'
    def index; end

    def new
      @badge = Badge.new
    end

    def create
      @badge = Badge.new(badge_params)

      if @badge.save
        redirect_to admin_badges_path(@badge), notice: t('.success')
      else
        render :new
      end
    end

    private

    def set_badge
      @badges = Badge.all
    end

    def badge_params
      params.require(:badge).permit(:title, :rule, :value, :img)
    end
  end
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/helpers/badge_helper.rb
# frozen_string_literal: true

module BadgeHelper
end

app/views/admin/badges/_badge.erb
<td class="align-middle"><%= badge.title %></td>
<td class="align-middle"><%= badge.rule %></td>
<td class="align-middle"><%= badge.value %></td>
<td class="align-middle"><%= badge.img %></td>
<td class="align-middle">
  <%= link_to t('.edit'),
              edit_admin_badge_path(badge),
              # data: { test_id: test.id },
              class: 'form-inline-link' %>
 </td>

<td class="align-middle"><%= link_to t('.delete'), admin_badge_path(badge), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/admin/badges/index.html.erb
<%#=render 'layouts/shared/errors',resource: @badges %>
<div class="row">
  <div class="col">
    <h1><%= t('.header') %></h1>
    <table class="table">
      <tr>
        <th class="sort-by-title pointer"><%= t('.title')%>
          <%=octicon 'arrow-up',class: 'text-success hide' %>
          <%=octicon 'arrow-down',class: 'text-success hide' %>
        </td>

        <th><%= t('.title') %></td>
        <th><%= t('.rule') %></td>
        <th><%= t('.value') %></td>
        <th><%= t('.img') %></td>
        <th><%= t('.action') %></td>

      </tr>

      <%= render @badges %>

    </table>
    <%=button_to t('.create_badge'), new_admin_badge_path,class: 'btn btn-success',method:  :get %>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="row">
  <%= form_with model: [:admin, @badge],local: true do |form| %>
    <%=render 'layouts/shared/errors',resource: @badge %>
    <p> <%=form.label t('.short_description') %>
      <%=form.text_field :title %>
    </p>
    <p> <%=form.label :rule %>
      <%=form.collection_select :rule,Badge.all,:rule,:rule %>
    </p>
    <p>
      <%=form.label :value %>
      <%=form.text_field :value%>
    </p>
    <p>
      <%=form.label :img %>
      <%=form.text_field :img%>
    </p>
<!--    <p> <%#=form.label :category_id %>-->
      <%#=form.collection_select :category_id, Category.all, :id,:title, prompt:true %>
<!--    </p>-->

    <p><%=form.submit %></p>

  <% end %>
</div>