config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations' }
  resources :feedback, only: %i[new create]
  resources :tests, only: :index do
    member do
      post :start
    end
  end
  resources :badges, only: :index
  resources :test_passages, only: %i[show update] do
    member do
      get :result # GET /tests_passages/10/result
      post :gist
    end
  end
  namespace :admin do
    resources :gists, only: :index
    resources :badges
    root 'tests#index'

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  validates :name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :users_badge
  has_many :users, through: :users_badge
  validates :title, :img, :rule, :value, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, presence: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests
  default_scope { order(title: :desc) }
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :gists
  has_many :answers
  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :questions
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, :timer, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level,
                                  message: 'Неуникальное значение уровня и названия теста' }
  scope :easy, -> { where(level: (0..1)) }
  scope :middle, -> { where(level: (2..4)) }
  scope :hard, -> { where(level: (5..Float::INFINITY)) }
  scope :sort_category, lambda { |category|
                          joins(:category)
                            .where(categories: { title: category })
                        }

  def self.test_sort(name)
    sort_category(name).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  scope :filter_complited, -> { where(complited: true) }
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  before_validation :before_validation_set_first_question, on: :create # после инициализация объекта класса TestPassage в памяти и после проверки на валидность будет вызов указанного метода
  before_validation :before_validation_set_next_question, on: :update
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.complited = 1 if success?
    save!
  end
  WIN_COUNT = 85
  def questions_count
    test.questions.count
  end

  def success?
    result? > WIN_COUNT
  end

  def progress_bar
    all_questions_number == 1 ? 0 : ((all_questions_number - 1) * 100) / questions_count
  end

  def all_questions_number
    test.questions.to_a.index(current_question) + 1
  end

  def result?
    test_all_questions_count = test.questions.count
    correct_questions_count = correct_questions
    (Float(correct_questions_count * 100) / test_all_questions_count).ceil
  end

  def correct_answer?(answer_ids)
    return if answer_ids.nil? # если юзер не сделает выбор

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def complited?
    current_question.nil?
  end

  def check_timer
    (created_at.to_i + self.test.timer * 60) > Time.now.to_i
  end

  def timer_end
    (created_at.to_i + self.test.timer * 60) - Time.now.to_i
  end

  private

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first if test.present?
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         authentication_keys: [:login]
  has_many :gists
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :tests_author, class_name: 'Test', foreign_key: 'author_id'
  has_many :users_badge
  has_many :badges, through: :users_badge
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true
  validates :login, presence: true, uniqueness: true

  def user_results(level)
    tests.where('level = ?', level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/users_badge.rb
# frozen_string_literal: true

class UsersBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
# frozen_string_literal: true

module Admin
  class GistsController < ApplicationController
    def index
      @gists = Gist.all
    end
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]
  def index
    @tests = Test.all
  end

  def start
    if @test.questions.any?

      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    else
      flash['warning'] = 'Администратор еще не добавил вопросов '
      redirect_to root_path
    end
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to(repo, "https://github.com/#{author}/#{repo}")
  end

  def flash_messages(flash)
    flash.map do |key, msg|
      tag.div(msg, id: key, class: 'flash alert')
    end.join.html_safe
  end
end

app/helpers/badge_helper.rb
# frozen_string_literal: true

module BadgeHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
# frozen_string_literal: true

module GistsHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(resource)
    if resource.persisted?
      "Edit #{resource.test.title} Question"
    else
      "Create New #{resource.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper

end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%=link_to 'Test-Guru',root_path,class: 'navbar-brand' %>
  <% if user_signed_in? %>
    <%=link_to "Gists",admin_gists_path %>
    Приветствуем, <%= current_user.name %> Guru  <%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>
  <% else %>
    <p class="nav user"><%= link_to 'Login', new_user_session_path %> | <%= link_to 'Signup', new_user_registration_path %></p>
  <% end %>
</nav>

app/views/layouts/_footer.erb
<footer>
  <p><%= current_year %></p>
  <p>Islam Gagiev</p>
  <p><%= github_url("SynthesisOne", "Test-Guru") %></p>
  <p>Test-Guru Повзоляет создавать и проходить тесты.</p>
  <p><a href="https://thinknetica.com/" target="_blank">Учебный проект в онлайн-школе Thinknetica</a></p>
 <%if current_user %>
    <p><%=link_to 'Оставить отзыв',new_feedback_path %> </p>
  <% end %>
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGuru Admin Panel</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
<%= render '/admin/nav' %>
<%= render 'layouts/shared/flash' %>

<%= yield %>

<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<div class="container">
  <%=render 'layouts/shared/flash' %>

  <%=render 'layouts/shared/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
</div>
  </body>

</html>

app/views/layouts/shared/_errors.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <p>
      <%= t('.header', count: resource.errors.count) %>
    </p>
    <% resource.errors.full_messages.each do |err| %>
      <div class="alert alert-danger"><%= err %></div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message.html_safe, class: "alert alert-info" %>
<% end %>

app/views/layouts/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">

  <%=link_to 'Test-Guru',root_path,class: 'navbar-brand' %>
  <% if user_signed_in? %>
    Приветствуем, <%= current_user.name %> Guru  <%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>
    <%if current_user.admin?%>
      <%=link_to "Панель админа",admin_tests_path %>
    <%end %>
  <% else %>
    <p class="nav user"><%= link_to 'Login', new_user_session_path %> | <%= link_to 'Signup', new_user_registration_path %></p>
  <% end %>
</nav>