config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations' }
  resources :feedback, only: %i[new create]
  resources :tests, only: :index do
    member do
      post :start
    end
  end
  resources :badges, only: :index
  resources :test_passages, only: %i[show update] do
    member do
      get :result # GET /tests_passages/10/result
      post :gist
    end
  end
  namespace :admin do
    resources :gists, only: :index
    resources :badges
    root 'tests#index'

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  scope :filter_complited, -> { where(complited: true) }
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  before_validation :before_validation_set_first_question, on: :create # после инициализация объекта класса TestPassage в памяти и после проверки на валидность будет вызов указанного метода
  before_validation :before_validation_set_next_question, on: :update
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.complited = 1 if success?
    save!
  end
  WIN_COUNT = 85
  def questions_count
    test.questions.count
  end

  def success?
    result? > WIN_COUNT
  end

  def progress_bar
    all_questions_number == 1 ? 0 : ((all_questions_number - 1) * 100) / questions_count
  end

  def all_questions_number
    test.questions.to_a.index(current_question) + 1
  end

  def result?
    test_all_questions_count = test.questions.count
    correct_questions_count = correct_questions
    (Float(correct_questions_count * 100) / test_all_questions_count).ceil
  end

  def correct_answer?(answer_ids)
    return if answer_ids.nil? # если юзер не сделает выбор

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def complited?
    current_question.nil?
  end

  def check_timer
    (created_at.to_i + self.test.timer * 60) > Time.now.to_i
  end

  def timer_end
    (created_at.to_i + self.test.timer * 60) - Time.now.to_i
  end

  private

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first if test.present?
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show result update gist]
  before_action :authenticate_user!

  def show; end

  def result
    flash[:timer] = 'Время вышло' unless @test_passage.check_timer || @test_passage.test.timer.zero?
  end

  def update
    if @test_passage.check_timer || @test_passage.test.timer.zero?
      @test_passage.accept!(params[:answers_ids])
      if @test_passage.complited?
        BadgeService.new(@test_passage).call if @test_passage.success?

        redirect_to result_test_passage_path(@test_passage)
      else
        render :show
      end
    else
      flash[:timer] = 'Время вышло'
      redirect_to result_test_passage_path(@test_passage)
    end
  end

  def gist
    connection = GistQuestionService.new(@test_passage.current_question)
    result = connection.call
    if connection.success?
      current_user.gists.create(question_id: @test_passage.current_question_id, link_to_gist: result.html_url)
      flash[:notice] =
        t('.success', gist_link: view_context.link_to('Gist', result.html_url, target: '_blank', rel: 'noopener'))
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @test_passage
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
end

app/views/test_passages/result.erb
<h1> <h1><%= t('.header', title: @test_passage.test.title) %></h1> </h1>
<% if @test_passage.success?%>
<h1 style="color: green">Вы сдали тест,ваш результат <%=  @test_passage.result? %>%</h1>
<%  else  %>
<h1 style="color: red">Вы не сдали тест,ваш результат <%=  @test_passage.result? %>%</h1>
<% end %>

app/views/test_passages/show.erb
<h1>Прохождение теста <%=@test_passage.test.title %></h1>
<div class="greyBar"><%= content_tag :div, "#{@test_passage.progress_bar}%", class: 'greenBar', data: { progress_bar: @test_passage.progress_bar } %>
</div>
<div>
  <span>Осталось времени:</span>
  <%=content_tag :span, '',class: 'timer',data: { timer: @test_passage.timer_end,test_passage_id: @test_passage.id }  %>
</div>



<b>
  <%=@test_passage.current_question.body %>
</b>

<%=form_with url: test_passage_path(@test_passage), local: true,method: :put do |form| %>
  <%=form.collection_check_boxes :answers_ids,@test_passage.current_question.answers, :id,:body,include_hidden: false do |b| %>

<p>
  <%= b.check_box id: "answer_id_#{b.object.id}"  %>
  <%= b.label %>
</p>
    <% end %>
 <p> <%=link_to 'Gist',gist_test_passage_path(@test_passage),method: :post %></p>
<%= form.submit 'Следующий вопрос' %>
<%end %>
<p>Вопрос <%= @test_passage.all_questions_number%> из <%=@test_passage.questions_count %> </p>