config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations' }
  resources :feedback, only: %i[new create]
  resources :tests, only: :index do
    member do
      post :start
    end
  end
  resources :badges, only: :index
  resources :test_passages, only: %i[show update] do
    member do
      get :result # GET /tests_passages/10/result
      post :gist
    end
  end
  namespace :admin do
    resources :gists, only: :index
    resources :badges
    root 'tests#index'

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  scope :correct, -> { where(correct: true) }
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

module Admin
  class AnswersController < Admin::BaseController
    before_action :set_answer, only: %i[show edit update destroy]
    before_action :find_question, only: %i[new create]

    def show; end

    def new
      @answer = @question.answers.new
    end

    def edit; end

    def create
      @answer = @question.answers.new(answer_params)

      if @answer.save
        redirect_to admin_question_path(@answer.question), notice: 'Ответ успешно создан'
      else
        render :new
      end
    end

    def update
      if @answer.update(answer_params)
        redirect_to @answer, notice: 'Ответ успешно обновлен'
      else
        render :edit
      end
    end

    def destroy
      @answer.destroy
      redirect_to @answer.question
    end

    private

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @answer, notice: 'Ответ успешно создан'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Ответ успешно обновлен'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/admin/answers/_answer.erb
 <li>
   <%=answer.body %>  <br>
   <%=link_to 'Show',admin_answer_path(answer) %>
   <%=link_to 'Edit',edit_admin_answer_path(answer) %>
   <%=link_to 'Delete',
              admin_answer_path(answer),
                       method: :delete,
                       data:{confirm: "Вы уверены?"}%>


 </li>

app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin,@question,@answer], local: true) do |form| %>
  <%=render 'layouts/shared/errors',resource: @answer %>
  <p> <%=form.label :body %>
    <%=form.text_area :body,id: :answer_body,rows:7,cols:60 %>
  </p>
  <p> <%=form.label :correct %>
    <%=form.check_box :correct,id: :answer_correct %>
  </p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', [:admin,@answer] %> |

<%= link_to 'Back', admin_answer_path(@answer) %>

app/views/admin/answers/new.html.erb
<h1>New Answer for <%=@question.body %></h1>

<%= render 'form' %>

app/views/admin/answers/show.html.erb
<h1>Вопрос:</h1>
<%=@answer.question.body %>
<p id="notice"><%= notice %></p>
<p>
  <b>Ответ:</b>
  <%=@answer.body %>
</p>
<p>
<p>
  <b>Ответ правильный?</b>
  <%=@answer.correct %>
</p>
<p>
  <b>Ответ:</b>
</p>
<%= link_to 'Edit', edit_admin_answer_path(@answer) %> |
<%= link_to 'Back', admin_question_path(@answer.question_id) %>